#! /usr/bin/env python3
"""Systhemer2.0 (Now in python!)"""
from logger import setup_logger
import toml
import Progs


class Settings:
    pass
    # theme_file_path = './files/theme.toml'


def convert_toml(path):
    """Takes path to toml file and return dictionary"""
    with open(path) as toml_file:
        return toml.loads(toml_file.read())


def run():
    """run program"""
    # initialize
    logger = setup_logger(Settings)
    Progs.setup(Settings)

    # load toml file
    logger.info('Loading theme/config file at: \'%s\'...',
                Settings.theme_file_path)
    try:
        theme = convert_toml(Settings.theme_file_path)
    except toml.TomlDecodeError as e:
        logger.critical('Syntax error in %s: %s',
                        Settings.theme_file_path, e)
        exit(1)
    except FileNotFoundError:
        logger.critical('File %s not found!', Settings.theme_file_path)
        exit(1)

    logger.debug('Theme file data: %s', theme)
    # toml file loaded
    # initialized

    # Apply theme
    # loop though program definitions
    for prog_def in Progs.prog_defs:
        # apply theme to curent program
        logger.info('Applying theme for program: \'%s\'',
                    prog_def.name)

        # loop through sections
        for section in theme:
            logger.debug('Applying section: %s', section)
            # loop through keys in current section
            for key in theme[section]:
                # set(key, value)
                prog_def.set(key, theme[section][key], section)

        # save theme for current program
        logger.info('Writing to config file for program: \'%s\'',
                    prog_def.name)
        prog_def.save()
    # theme applied


def parse_args():
    parser = argparse.ArgumentParser(description='Systhemer: System theming'
                                     'utility designed for ease of sharing')
    parser.add_argument('-v',
                        '--verbose',
                        help='set level of verbosity',
                        action='count',
                        default=0)
    parser.add_argument('-nc',
                        '--no-colorlog',
                        help='disable colorlog',
                        action='store_true')
    parser.add_argument('path',
                        help='path to theme file',
                        action='store')

    parser.parse_args(namespace=Settings)
    # {nothing} : WARNING, -v : INFO, -vv : DEBUG, -v*{anything more}, DEBUG
    Settings.verbose = 30 - Settings.verbose*10
    Settings.theme_file_path = Settings.path


if __name__ == '__main__':
    import argparse
    parse_args()
    run()
