#! /usr/bin/env python3
"""Systhemer2.0 (Now in python!)"""
from logger import setup_logger
import interactive
import logging
import configparser
import Progs
from Progs.value import Litteral


class Settings:
    # default settings...
    colorlog_supported = True
    VDEBUG_LVL = 9
    # theme_file_path = './files/theme.toml'


def run():
    """run program"""
    # initialize
    # load ini file
    logger.info('Loading theme/config file at: \'%s\'...',
                Settings.theme_file_path)
    theme_p = configparser.ConfigParser()
    if not theme_p.read(Settings.theme_file_path):
        logger.critical('File %s not found!', Settings.theme_file_path)
        exit(1)
    theme = theme_p._sections

    logger.log(Settings.VDEBUG, 'Theme file data: %s', theme)
    # ini file loaded
    # initialized

    # Build values dict
    logger.info('Building values dictionary')

    values = {}
    for pd in Progs.prog_defs:
        logger.info('Building values for program: \'%s\'', pd.get_name())

        for rule in theme:
            values[rule] = {}
            for key in theme[rule]:
                val_type = pd.get_key_type(key)
                if val_type:
                    values[rule][key] \
                            = val_type.Formatter.auto_parse(theme[rule][key])
        for rule in theme:
            for key in theme[rule]:
                if key not in values[rule]:
                    logger.log(Settings.VDEBUG, 'unrecognized key \'%s\' '
                               'assuming string litteral', key)
                    values[rule][key] = Litteral(theme[rule][key])

    logger.log(Settings.VDEBUG, values)
    logger.info('Values dictionary built')
    # value dict built

    # Apply theme
    # loop though program definitions
    for prog_def in Progs.prog_defs:
        # apply theme to curent program
        logger.info('Applying theme for program: \'%s\'',
                    prog_def.get_name())

        # loop through rules
        for rule in values:
            logger.debug('Applying rule: %s', rule)
            # loop through keys in current rule
            for key in values[rule]:
                # set(key, value)
                prog_def.set(key, values[rule][key], rule)

        # save theme for current program
        logger.info('Writing to config file for program: \'%s\'',
                    prog_def.get_name())
        prog_def.save()
    # theme applied


def parse_args():
    parser = argparse.ArgumentParser(description='Systhemer: System theming'
                                     'utility designed for ease of sharing')
    parser.add_argument('-i',
                        '--interactive',
                        help='run Systhemer in interactive mode',
                        action='store_true')
    parser.add_argument('-v',
                        '--verbose',
                        help='set level of verbosity',
                        action='count',
                        default=0)
    parser.add_argument('-l',
                        '--list',
                        help='list supported programs',
                        action='store_true',)
    parser.add_argument('--VDEBUG_LVL',
                        help='set VDEBUG_LVL',
                        action='store')
    if Settings.colorlog_supported:
        parser.add_argument('-nc',
                            '--no-colorlog',
                            help='disable colorlog',
                            action='store_true')
    parser.add_argument('path',
                        help='path to theme file',
                        action='store',
                        nargs='?')

    parser.parse_args(namespace=Settings)
    Settings.VDEBUG = Settings.VDEBUG_LVL
    # {nothing} : WARNING,
    # -v : INFO,
    # -vv : DEBUG,
    # -vvv : VDEBUG,
    # -v*{anything more} : VDEBUG
    levels = {1: logging.INFO, 2: logging.DEBUG, 3: Settings.VDEBUG_LVL}
    if Settings.verbose in levels:
        Settings.verbose = levels[Settings.verbose]
    elif Settings.verbose > 3:
        Settings.verbose = Settings.VDEBUG_LVL
    else:
        Settings.verbose = logging.WARNING
    Settings.theme_file_path = Settings.path


def list_progs():

    for p in Progs.prog_defs:
        if p.is_installed():
            print(p.get_name())


if __name__ == '__main__':
    import argparse
    try:
        import colorlog
    except ImportError:
        Settings.colorlog_supported = False
        Settings.nocolorlog = True

    parse_args()
    logger = setup_logger(Settings)
    Progs.setup(Settings)
    if Settings.interactive:
        interactive.iconsole(Settings).cmdloop()
    elif Settings.list:
        list_progs()
    else:
        if getattr(Settings, 'path', None):
            run()
        else:
            logger.critical('Error argument: \'path\' not specified!')
            exit(1)
